services:
  seed:
    build: medusa-starter-default
    command: yarn seed
    restart: "no"
    ports:
      - 9001:9001
    networks:
      - medusa-network
    environment:
      REDIS_URL: redis://redis:6379
      CACHE_REDIS_URL: redis://redis:6379
      EVENTS_REDIS_URL: redis://redis:6379
      WE_REDIS_URL: redis://redis:6379
      DATABASE_URL: postgres://medusa-starter:medusa-password@postgres/medusa-starter?ssl_mode=disable
      POSTGRES_URL: postgres://medusa-starter:medusa-password@postgres/medusa-starter?ssl_mode=disable

networks:
  medusa-network:
