services:
  frontend:
    build:
      context: nextjs-starter-medusa
      args:
        - NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=pk_a6d3ffd9fe782581341e5dbf3cc34203f01d71f169663cbd54cd59ab87f9cf17
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 1024M
    volumes:
      - storefront-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  storefront-data:
