services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: medusa-starter
      POSTGRES_PASSWORD: medusa-password
      POSTGRES_DB: medusa-starter
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 1024M
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "medusa-starter"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - cache-backend-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  cache-backend-data:
